remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Guide de Voyage Houston 2025
description: Guide complet pour le voyage à Houston et le FIRST Championship 2025

# Navigation
show_downloads: false
google_analytics:
